project:
  type: website
  output-dir: docs

website:
  title: "acéphale"
  site-url: https://andrewallenbruce.github.io/acephale/
  repo-url: https://github.com/andrewallenbruce/acephale
  description: "Learning for Getting Ahead"
  open-graph:
    locale: en_US
  twitter-card:
    creator: "@andrewallbruce"
  back-to-top-navigation: true
  navbar:
    right:
      - icon: github
        href: https://github.com/andrewallenbruce
      - icon: twitter
        href: https://twitter.com/andrewallbruce
      - icon: linkedin
        href: https://www.linkedin.com/in/andrewallenbruce/
  page-footer:
    left: "© Copyright 2024 Andrew Allen Bruce. Except where otherwise noted, all text and images licensed CC-BY-NC 4.0."

format:
  html:
    theme:
      - zephyr
      - custom.scss
    fontsize: 18px
    linestretch: 1.75
    embed-resources: false
    number-depth: 2
    fig-width: 8
    fig-height: 5
    fig-align: center
    output-width: 100%
    highlight-style: tango
