project:
  type: website
  output-dir: docs

website:
  title: "acéphale"
  site-url: https://andrewallenbruce.github.io/acephale/
  repo-url: https://github.com/andrewallenbruce/acephale
  description: "Learning for Getting A Head"
  open-graph:
    locale: en_US
  twitter-card:
    creator: "@andrewallbruce"
  back-to-top-navigation: true
  navbar:
    right:
      - icon: github
        href: https://github.com/andrewallenbruce
      - icon: twitter
        href: https://twitter.com/andrewallbruce
      - icon: linkedin
        href: https://www.linkedin.com/in/andrewallenbruce/
  page-footer:
    left: "© Copyright 2024 Andrew Allen Bruce."

format:
  html:
    theme: [morph, styles.css]
    linestretch: 1.75
    output-width: 100%
