project:
  type: website

website:
  title: "acéphale"
  back-to-top-navigation: true
  navbar:
    right:
      - icon: github
        href: https://github.com/andrewallenbruce
      - icon: twitter
        href: https://twitter.com/andrewallbruce
      - icon: linkedin
        href: https://www.linkedin.com/in/andrewallenbruce/
format:
  html:
    theme:
      - lux
      - styles.scss
    fontsize: 16px
    linestretch: 1.75
    embed-resources: false
    number-depth: 2
    fig-width: 8
    fig-height: 5
    fig-align: center
    output-width: 100%
    highlight-style: tango
    site-url: https://andrewallenbruce.github.io/acephale/
    repo-url: https://github.com/andrewallenbruce/acephale
