project:
  type: website
  output-dir: docs

website:
  title: "acéphale"
  site-url: https://andrewallenbruce.github.io/acephale/
  repo-url: https://github.com/andrewallenbruce/acephale
  description: "Learning for Getting A Head"
  page-navigation: true
  open-graph:
    locale: en_US
  twitter-card:
    creator: "@andrewallbruce"
  back-to-top-navigation: true
  navbar:
    right:
      - icon: github
        href: https://github.com/andrewallenbruce
      - icon: twitter
        href: https://twitter.com/andrewallbruce
      - icon: linkedin
        href: https://www.linkedin.com/in/andrewallenbruce/
  page-footer:
    left: "© Copyright 2024 Andrew Allen Bruce."

format:
  html:
    theme: [sandstone, custom2.scss]
    grid:
      body-width: 900px
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai

execute:
  freeze: auto  # re-render only when source changes
