---
title: "Medical Codes as Matrices"
format:
  html:
    reference-location: block
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: setup
#| echo: true
#| message: false
#| warning: false

knitr::opts_chunk$set(
  dev = "ragg_png",
  dpi = 320,
  out.width = "100%",
  fig.width = 8,
  fig.asp = 0.818,
  fig.retina = 2,
  fig.align = "center",
  fig.show = "hold"
)
options(scipen = 999)

library(tidyverse)
library(stringfish)
library(ggthemes)
library(paintr)
library(fuimus)
library(procedural)
library(northstar)
```

# Coding Terminologies

```{r}
#| label: pcs_list
#| echo: true
#| message: false
#| warning: false
pcs <- dplyr::lst(
  c = c(0:9, fuimus::splitter("ABCDEFGHJKLMNPQRSTUVWXYZ")),
  p = rlang::seq2_along(1, c),
  a = 1:7)

pcs
```


```{r}
#| label: hcpcs_list
#| echo: true
#| message: false
#| warning: false
hcpcs <- dplyr::lst(
  c = c(0:9, fuimus::splitter("ABCEFGHJKLMPQRSTUV")),
  p = rlang::seq2_along(1, c),
  a = 1:5)

hcpcs
```

## Lookup

```{r}
#| label: lookup
#| echo: true
#| message: false
#| warning: false
look <- \(code, constants, possible) {
  
  code <- fuimus::splitter(
    stringfish::sf_toupper(code))
  
  names(possible) <- constants
  
  unname(possible[code])
}

look("0G9000Z", pcs$c, pcs$p)

look("99213", hcpcs$c, hcpcs$p)
```

## Make Matrix

```{r}
#| label: medtrix
#| echo: true
#| message: false
#| warning: false
medtrix <- \(code, system) {
  
  constants <- system$c
  possible  <- system$p
  axis      <- system$a
  
  m <- matrix(data     = 0L,
              nrow     = length(constants),
              ncol     = length(axis),
              dimnames = list(constants, axis))
  
  x <- look(code, constants, possible)
  
  for (i in axis) { m[x[i], i] <- 1L }
  
  return(m)
}
```

**ICD-10-PCS:**

```{r}
#| label: medtrix_pcs
#| echo: true
#| message: false
#| warning: false
medtrix(code = "0G9000Z", system = pcs)
```

**HCPCS (CPT):**

```{r}
#| label: medtrix_hcpcs
#| echo: true
#| message: false
#| warning: false
medtrix(code = "99213", system = hcpcs)
```

# Plot Matrix

```{r}
#| echo: true
#| message: false
#| warning: false
mpcs <- medtrix(code = "0G9000Z", system = pcs)

gpaint_matrix(
  mpcs, 
  highlight_area = mpcs == 1, 
  show_indices = "none",
  graph_title = "ICD-10-PCS Code 0G9000Z",
  graph_subtitle = NULL) + 
  theme_solid() + 
  ylim(rev(rownames(mpcs))) + 
  xlim(colnames(mpcs)) + 
  xlab("") + 
  ylab("") +
  theme(
    legend.position = "none",
    axis.text.x = element_text(size = 11),
    axis.text.y = element_text(size = 11),
    axis.ticks.x = element_blank(),
    axis.ticks.y = element_blank())
```

```{r}
#| echo: true
#| message: false
#| warning: false
mhcpcs <- medtrix(code = "99213", system = hcpcs)

gpaint_matrix(
  mhcpcs, 
  highlight_area = mhcpcs == 1, 
  show_indices = "none",
  graph_title = "HCPCS Code 99213",
  graph_subtitle = NULL) + 
  theme_solid() + 
  ylim(rev(rownames(mhcpcs))) + 
  xlim(colnames(mhcpcs)) + 
  xlab("") + 
  ylab("") +
  theme(
    legend.position = "none",
    axis.text.x = element_text(size = 11),
    axis.text.y = element_text(size = 11),
    axis.ticks.x = element_blank(),
    axis.ticks.y = element_blank())
```


{{< pagebreak >}}


# Session Information

```{r}
#| label: sessioninfo
#| echo: false
#| eval: true
sessioninfo::session_info(pkgs = "loaded", info = "packages")
```
