---
title: "provider: Comprehensive Search"
format:
  html:
    reference-location: block
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: setup
#| echo: false
#| message: false
#| warning: false

knitr::opts_chunk$set(
  dev = "ragg_png",
  dpi = 320,
  out.width = "100%",
  fig.width = 8,
  fig.asp = 0.818,
  fig.retina = 2,
  fig.align = "center",
  fig.show = "hold"
)
options(scipen = 999, digits = 3)

library(tidyverse)
library(fastverse)
library(provider)
library(arktax)
library(S7)
```

# S7 Sketch

## API Examples

### NPPES

```{r}
#| label: sources_nppes
nppes(npi = 1043245657) |> glimpse()
```

### Taxonomy

```{r}
#| label: sources_taxonomy
ex_tx = "207ZB0001X"
```

::: {.panel-tabset}

## Display

```{r}
#| label: sources_taxonomy_display
tx_dis <- taxonomy_display(
  taxonomy_code = ex_tx
  )[["taxonomy_display"]]

cat(tx_dis)
```

## Definition

```{r}
#| label: sources_taxonomy_definition
tx_def <- taxonomy_definition(
  taxonomy_code = ex_tx
  )[["taxonomy_definition"]]

cat(tx_def)
```

## Hierarchy

```{r}
#| label: sources_taxonomy_hierarchy
tx_hier <- taxonomy_hierarchy(
  taxonomy_code = ex_tx
  )[, 2:3]

tx_hier
```

## Changelog

```{r}
#| label: sources_taxonomy_changelog
tx_chg <- taxonomy_changelog(
  taxonomy_code = ex_tx
  )[, 2:4]

tx_chg
```

## Console

```{r}
#| label: sources_taxonomy_console
utils::formatOL(
  c(
    "Section: ",
    "Grouping: ",
    "Classification: ",
    "Specialization: "
    ),
  type = "I",
  offset = 2
  ) |> 
  writeLines()

# view_length <- \(x) {
#   grp_name <- format(seq_along(x))
#   grp_size <- format(vlen(x), justify = "left")
#   grp_mems <- unname(x)
#   grp_mems <- if (empty(grp_mems)) NULL else format(grp_mems, justify = "none")
#   cli::cat_bullet(glue::glue("{grp_name}: ", "{grp_size}|", "-[{grp_mems}]"))
#   return(invisible(x))
# }
```


::: 

<hr>

### Medicare Enrollment

```{r}
#| label: sources_providers
providers(npi = 1043245657) |> glimpse()
```

```{r}
#| label: sources_clinicians
clinicians(npi = 1043245657) |> glimpse()
```

```{r}
#| label: sources_opt_out
#| eval: false
opt_out(npi = 1043245657)
```

```{r}
#| label: sources_order_refer
order_refer(npi = 1043245657)
```

```{r}
#| label: sources_reassign
reassignments(npi = 1043245657) |> glimpse()
```

```{r}
#| label: sources_affiliations
affiliations(npi = 1043245657) |> glimpse()
```

```{r}
#| label: sources_hospitals
hospitals(facility_ccn = 470003) |> glimpse()

hospitals(facility_ccn = 330250) |> glimpse()
```

## Provider Class

```{r}
#| label: provider_s7class
Provider <- new_class(
  name = "Provider", 
  abstract = TRUE,
  properties = list(
    npi = class_character,
    entity = class_factor
  ))
```

### Individual Class

```{r}
#| label: individual_s7class
Individual <- new_class(
  name = "Individual",
  parent = Provider,
  properties = list(
    npi = new_property(NULL | class_character),
    entity = new_property(NULL | class_character),
    demographics = new_property(class_list, 
      default = list(
        prefix = class_character,
        first_name = class_character,
        middle_name = class_character,
        last_name = class_character,
        suffix = class_character,
        gender = class_character,
        credential = class_character,
        sole_proprietor = class_logical,
        medical_school = class_character,
        graduation_year = class_integer
      )),
    dates = new_property(
      class_list, 
      default = list(
        updated = class_Date,
        enumerated = class_Date,
        certified = class_Date
      )),
    address = new_property(
      class_list, 
      default = list(
        purpose = class_character,
        street = class_character,
        city = class_character,
        state = class_character,
        postal_code = class_character,
        country = class_character,
        phone = class_character,
        fax = class_character
      )),
    taxonomy = new_property(
      class_list, 
      default = list(
        code = class_character,
        primary = class_logical,
        description = class_character,
        license = class_character,
        state = class_character
      )),
    identifier = new_property(
      class_list, 
      default = list(
        code = class_character,
        indicator = class_character,
        issuer = class_character,
        state = class_character
      )),
    enrollment = new_property(class_list, 
      default = list(
        pac = new_property(NULL | class_character),
        enid = new_property(NULL | class_character),
        specialty = new_property(
          class_list, 
          default = list(
            code = class_character, 
            description = class_character)),
        state = class_character,
        # opt_out = new_property(class_logical | class_list),
        order_refer = new_property(
          class_list, 
          default = list(
          MedicareB = class_logical,
          HHA = class_logical,
          DME = class_logical,
          PMD = class_logical,
          Hospice = class_logical))))))
```

#### Example

```{r}
#| label: individual_s7class_example
fung_ex <- Individual(
  npi = "1043245657",
  entity = "I",
  demographics = list(
    prefix = "DR",
    first_name = "MARK",
    middle_name = "K",
    last_name = "FUNG",
    suffix = NA_character_,
    gender = "Male",
    credential = "MD, PhD",
    sole_proprietor = FALSE,
    medical_school = NA_character_,
    graduation_year = 1999L),
  dates = list(
    updated = as.Date("2013-10-08"),
    enumerated = as.Date("2006-07-11"),
    certified = as.Date("2021-07-01")),
  address = list(
    purpose = "Practice",
    street = "111 COLCHESTER AVE",
    city = "BURLINGTON",
    state = "VT",
    postal_code = "05401",
    country = "US",
    phone = "802-847-3000",
    fax = "802-847-3509"),
  taxonomy = list(
    code = "207ZB0001X",
    primary = TRUE,
    description = "Pathology, Blood Banking & Transfusion Medicine",
    license = "042-0010655",
    state = "VT"),
  identifier = list(
    code = "1010070",
    indicator = "05",
    issuer = "MEDICAID",
    state = "VT"),
  enrollment = list(
    pac = "7810891009",
    enid = "I20031120000251",
    specialty = list(
      code = "14-22",
      description = "PRACTITIONER - PATHOLOGY"),
    state = "VT",
    order_refer = list(
      MedicareB = TRUE,
      HHA = TRUE,
      DME = TRUE,
      PMD = TRUE,
      Hospice = TRUE)))

fung_ex
```

<hr>

## Session Information 

```{r}
#| echo: false
pander::pander(sessionInfo())
```
